name: Cache .NET Workloads
description: Cache .NET workload assets for Android/MAUI builds

inputs:
  dotnet-version:
    description: '.NET SDK version'
    required: true
  cache-version:
    description: 'Cache key version; bump to invalidate (default 2 to clear stale caches)'
    required: false
    default: '2'

runs:
  using: composite
  steps:
    - name: Cache .NET workloads and assets
      uses: actions/cache@v4
      with:
        path: |
          ~/.dotnet/workloads
          ~/.dotnet/packs
          ~/.dotnet/sdk-manifests
          ~/.dotnet/toolResolverCache
          C:\Program Files\dotnet\sdk-manifests
        key: ${{ runner.os }}-dotnet-workloads-android-${{ inputs.cache-version }}-${{ inputs.dotnet-version }}
        restore-keys: |
          ${{ runner.os }}-dotnet-workloads-android-${{ inputs.cache-version }}-
          ${{ runner.os }}-dotnet-workloads-android-
